baseurl = "https://sathishram12.github.io/portfolio-hugo/" # Hostname (and path) to the root.
title = "Sathish Ram Murugan" # Site title.
theme = "coder-portfolio" # Set the theme.
languagecode = "en" # The site’s language code used to generate RSS.
defaultcontentlanguage = "en" # The default content language.

paginate = 20 # Default number of pages per page in pagination.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.
pygmentsUseClasses = true # new add

disqusShortname = "yourdiscussshortname" # Enable or disable Disqus.

[params] # theme parameters
    author = "Sathish Ram Murugan" # Author's name.
    info = "IoT Engineer and AI Enthusiast" # Author's job title or info.
    description = "Sathish Ram Murugan's portfolio" # Site description.
    keywords = "blog,developer,personal" # Site keywords.
    avatarurl = "images/sathish.jpg" # Contain the path of the optionnal avatar in the static folder.

    footercontent = "Enter a text here." # Add footer content
    fixedbarContent = "Do you want to know me more private?→" # Add fixedbar content
    fixedbarContentAfter = "Thank You! Please share it if you like it→" # Add fixedbar content after click

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = false
    hideCopyright = false

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    # Bottom sns share
    snsShare = true # new add
    # Popular sns share
    # if you want add sns. please message!
    enableTwitterShare = true  # new add
    enableFacebookShare = true # new add
    enableHatenaShare = true   # new add
    enableLineShare = true     # new add
    enableLinkedInShare = true # new add

    thumbnail = "images/tn.png" # default sns thumbnail

    # Multilanguage mode
    langseparator = "|" # Separates menus from language selectors when site is multilingual.

[languages]
    [languages.en]
        languagename = "English" # The language name to be displayed in the selector.
        title = "Sathish Ram Murugan"

        # You can configure the theme parameter for each language. 
        [languages.en.params]
        author = "Sathish Ram Murugan"
        info = "IoT Engineer and AI enthusiast"
        description = "Sathish Ram Murugan's portfolio"
        keywords = "blog,developer,personal"

        [languages.en.menu] # It is possible to change the menu too.

        [[languages.en.menu.main]]
        name = "About"
        weight = 1.0
        url = "about"

        [[languages.en.menu.main]]
        name = "Blog"
        weight = 2.0
        url = "posts"


    [languages.De]
        languagename = "Deutsch"
        title = "Sathish Ram Murugan"

        [languages.De.params]
            author = "Sathish Ram Murugan"
            description = "Sathish Ram Murugan's portfolio"
            keywords = "blog,Entwickler, persönlich"
            info = "IoT-Ingenieur und KI-Enthusiast"

        [languages.De.menu]

            [[languages.De.menu.main]]
            name = "Über"
            weight = 1.0
            url = "De/about"

            [[languages.De.menu.main]]
            name = "Beiträge"
            weight = 2.0
            url = "ja/posts"

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/sathishram12"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 2
    url = ""
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/satzramembd"
[[params.social]]
    # If icon is not set, Text is displayed.
    name = "LinkedIn"
    weight = 4
    url = "https://www.linkedin.com/in/satzramembd"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "posts"
[[menu.main]]
    name = "About"
    weight = 2
    url = "about"

